version: '3.9'

services:
  db:
    image: postgres
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${DB_NAME}",
          "-U",
          "${DB_USER}"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
      start_period: 10s
    container_name: nasa_images
    working_dir: /application
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: core_api
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  astrolog:
      build:
        dockerfile: ./Dockerfile
      depends_on:
        db:
          condition: service_healthy
      ports:
        - 5632:5632
